# -*- coding: utf-8 -*-
"""Weekly Project 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BAZReBPLnmp_SWuXfjFmLRcoGgSdbUKm
"""

pip install faker

"""Importing Libraries"""

import pandas as pd
import numpy as np
from faker import Faker

fake = Faker()

"""Creating Data Sets"""

num_students = 250

student_ids = [f'S{i:03d}' for i in range(1, num_students + 1)]
names = [fake.name() for _ in range(num_students)]
genders = np.random.choice(['Male', 'Female'], num_students)
departments = np.random.choice(['CSE', 'IT', 'ECE'], num_students)
years = np.random.choice(['1st', '2nd', '3rd'], num_students)
maths_marks = np.random.randint(40, 100, num_students)
science_marks = np.random.randint(40, 100, num_students)
english_marks = np.random.randint(40, 100, num_students)
attendance = np.random.randint(50, 101, num_students)
internal_marks = np.random.randint(0, 26, num_students)

students_data = pd.DataFrame({
    'Student_ID': student_ids,
    'Name': names,
    'Gender': genders,
    'Department': departments,
    'Year': years,
    'Maths': maths_marks,
    'Science': science_marks,
    'English': english_marks,
    'Attendance (%)': attendance,
    'Internal Marks': internal_marks
})

display(students_data)

"""Data Cleaning"""

print('Missing values before cleaning:')
display(students_data.isnull().sum())

"""Data Preprocessing or Information"""

print('\nData types before cleaning:')
display(students_data.info())

"""Descriptive Statistics

*   Mean
*   Median
*   Mode
*   Standard Deviation


"""

numerical_cols = ['Maths', 'Science', 'English', 'Attendance (%)', 'Internal Marks']

print('\nMean of each numerical column:')
display(students_data[numerical_cols].mean())

print('\nMedian of each numerical column:')
display(students_data[numerical_cols].median())

print('\nMode of each numerical column:')

for col in numerical_cols:
    print(f'- {col}: {students_data[col].mode().tolist()}')

print('\nStandard Deviation of each numerical column:')
display(students_data[numerical_cols].std())

"""Students Performance Metrics

*   Total Marks
*   Average Marks
*   Grade Classification


"""

students_data['Total Marks'] = students_data['Maths'] + students_data['Science'] + students_data['English']
students_data['Average Marks'] = students_data['Total Marks'] / 3

def get_grade(average_marks):
    if average_marks >= 90:
        return 'A'
    elif average_marks >= 80:
        return 'B'
    elif average_marks >= 70:
        return 'C'
    elif average_marks >= 60:
        return 'D'
    else:
        return 'F'

students_data['Grade'] = students_data['Average Marks'].apply(get_grade)

print('Students Data with Performance Metrics:')
display(students_data.head())

"""### Department-wise Performance"""

department_performance = students_data.groupby('Department')['Average Marks'].mean().reset_index()
print('Average Marks by Department:')
display(department_performance)

"""### Gender-wise Comparison"""

gender_comparison = students_data.groupby('Gender')['Average Marks'].mean().reset_index()
print('\nAverage Marks by Gender:')
display(gender_comparison)

"""### Relationship between Attendance and Marks"""

import matplotlib.pyplot as plt
import seaborn as sns

correlation_attendance_marks = students_data['Attendance (%)'].corr(students_data['Average Marks'])
print(f"Correlation between Attendance and Average Marks: {correlation_attendance_marks:.2f}")

plt.figure(figsize=(8, 6))
sns.scatterplot(x='Attendance (%)', y='Average Marks', data=students_data)
plt.title('Attendance (%) vs Average Marks')
plt.xlabel('Attendance (%)')
plt.ylabel('Average Marks')
plt.grid(True)
plt.show()

"""### Relationship between Internal Marks and Final Performance"""

correlation_internal_marks = students_data['Internal Marks'].corr(students_data['Average Marks'])
print(f"Correlation between Internal Marks and Average Marks: {correlation_internal_marks:.2f}")

plt.figure(figsize=(8, 6))
sns.scatterplot(x='Internal Marks', y='Average Marks', data=students_data)
plt.title('Internal Marks vs Average Marks')
plt.xlabel('Internal Marks')
plt.ylabel('Average Marks')
plt.grid(True)
plt.show()

"""### Year-wise Trends"""

year_trends = students_data.groupby('Year')['Average Marks'].mean().reset_index()
print('\nAverage Marks by Year:')
display(year_trends)

top_performing_students = students_data[students_data['Grade'] == 'A']
print('Top Performing Students (Grade A):')
display(top_performing_students.head())

low_performing_students = students_data[students_data['Grade'] == 'F']
print('\nLow Performing Students (Grade F):')
display(low_performing_students.head())

"""### Data Visualization"""

import matplotlib.pyplot as plt
import seaborn as sns

# Bar Chart: Distribution of students by Department
plt.figure(figsize=(10, 6))
sns.countplot(x='Department', data=students_data, palette='viridis')
plt.title('Distribution of Students by Department')
plt.xlabel('Department')
plt.ylabel('Number of Students')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# Bar Chart: Distribution of students by Gender
plt.figure(figsize=(8, 5))
sns.countplot(x='Gender', data=students_data, palette='mako')
plt.title('Distribution of Students by Gender')
plt.xlabel('Gender')
plt.ylabel('Number of Students')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# Histogram: Distribution of Average Marks
plt.figure(figsize=(10, 6))
sns.histplot(students_data['Average Marks'], bins=10, kde=True, color='skyblue')
plt.title('Distribution of Average Marks')
plt.xlabel('Average Marks')
plt.ylabel('Frequency')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# Pie Chart: Grade Distribution
grade_counts = students_data['Grade'].value_counts().sort_index()
plt.figure(figsize=(8, 8))
plt.pie(grade_counts, labels=grade_counts.index, autopct='%1.1f%%', startangle=140, colors=sns.color_palette('pastel'))
plt.title('Overall Grade Distribution')
plt.axis('equal') # Equal aspect ratio ensures that pie is drawn as a circle.
plt.show()